'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Camera,RotateCw} from 'lucide-react';
export default function BarcodeScanner({open,onClose,onDetected}:{open:boolean;onClose:()=>void;onDetected:(code:string)=>void}){const video=useRef<HTMLVideoElement>(null),callback=useRef(onDetected),[error,setError]=useState(''),[facing,setFacing]=useState('environment'),[retry,setRetry]=useState(0),[reading,setReading]=useState(false);callback.current=onDetected;
useEffect(()=>{if(!open)return;let cancelled=false,found=false;let controls:{stop:()=>void}|undefined;let stream:MediaStream|undefined;const stop=()=>{controls?.stop();stream?.getTracks().forEach(t=>t.stop())};setError('');const start=async()=>{try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('กล้องไม่พร้อม กรุณาเปิดเว็บใน Safari หรือ Chrome');const {BrowserMultiFormatReader}=await import('@zxing/browser');if(cancelled)return;stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:720}}});if(cancelled){stop();return;}const reader=new BrowserMultiFormatReader();controls=await reader.decodeFromStream(stream,video.current!,(result,_error,c)=>{if(result&&!cancelled&&!found){found=true;c.stop();stop();callback.current(result.getText())}});if(cancelled||found)stop();}catch(e:any){stop();if(!cancelled)setError(e.name==='NotAllowedError'?'กรุณาอนุญาตกล้องในการตั้งค่าเว็บไซต์ แล้วกดลองอีกครั้ง':e.name==='NotFoundError'?'ไม่พบกล้อง ลองเลือกภาพบาร์โค้ดด้านล่าง':'เปิดกล้องไม่สำเร็จ ลองอีกครั้ง หรือเลือกภาพบาร์โค้ด');}};start();const hide=()=>{if(document.hidden){cancelled=true;stop();setError('กล้องหยุดเมื่อสลับแอป กดลองอีกครั้งเพื่อเปิดกล้อง')}};document.addEventListener('visibilitychange',hide);return()=>{cancelled=true;stop();document.removeEventListener('visibilitychange',hide)}},[open,facing,retry]);
async function readImage(file?:File){if(!file)return;if(file.size>12*1024*1024){setError('กรุณาเลือกรูปไม่เกิน 12 MB');return;}setReading(true);setError('');const url=URL.createObjectURL(file);try{const {BrowserMultiFormatReader}=await import('@zxing/browser');const result=await new BrowserMultiFormatReader().decodeFromImageUrl(url);callback.current(result.getText())}catch{setError('อ่านบาร์โค้ดไม่พบ ลองถ่ายใหม่ให้เส้นบาร์โค้ดชัดและเห็นครบ')}finally{URL.revokeObjectURL(url);setReading(false)}}
return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="pos-dialog scanner-dialog"><DialogHeader><DialogTitle>สแกนบาร์โค้ด</DialogTitle><DialogDescription>เล็งกล้องให้เห็นบาร์โค้ดครบแนว หลีกเลี่ยงแสงสะท้อน</DialogDescription></DialogHeader><div className="scanner-camera"><video ref={video} autoPlay muted playsInline/><div className="scanner-guide" aria-hidden="true"/></div>{error&&<p role="alert" className="notice">{error}</p>}<div className="actions wrap"><button className="secondary" onClick={()=>setFacing(f=>f==='environment'?'user':'environment')}><Camera size={17}/>สลับกล้อง</button><button className="secondary" onClick={()=>setRetry(r=>r+1)}><RotateCw size={17}/>ลองอีกครั้ง</button></div><label className="field"><span>{reading?'กำลังอ่านภาพ…':'หรือเลือก / ถ่ายภาพบาร์โค้ด'}</span><input disabled={reading} type="file" accept="image/*" onChange={e=>readImage(e.target.files?.[0])}/></label><p className="muted">รองรับบาร์โค้ดสินค้าทั่วไป เช่น EAN, UPC และ Code 128</p></DialogContent></Dialog>;
}
