'use client';
import {useEffect,useMemo,useState} from 'react';
import {Download,FileSpreadsheet,UploadCloud} from 'lucide-react';

type Product={id:string;name:string;barcode:string;scan_code?:string|null;category:string;stock:number;unit:string;cost:number|null;price:number;low_stock:number;active:number};

export function ExcelManager({reload,products,categories}:{reload:()=>Promise<void>;products?:Product[];categories?:string[]}){
  const [mode,setMode]=useState<'import'|'export'>('import'),[rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(0),[batchId,setBatchId]=useState(''),[result,setResult]=useState(''),[exportCategory,setExportCategory]=useState('ทั้งหมด'),[selected,setSelected]=useState<string[]>([]);
  const [availableProducts,setAvailableProducts]=useState<Product[]>(products||[]),[availableCategories,setAvailableCategories]=useState<string[]>(categories||[]);
  useEffect(()=>{if(products?.length){setAvailableProducts(products);setAvailableCategories(categories||[]);return}fetch('/api/data',{cache:'no-store'}).then(r=>r.json()).then(d=>{setAvailableProducts(d.products||[]);setAvailableCategories(['ทั้งหมด',...(d.categories||[])])}).catch(()=>setError('โหลดรายการสินค้าไม่สำเร็จ'))},[]);
  const exportRows=useMemo(()=>availableProducts.filter(p=>p.active!==0&&(exportCategory==='ทั้งหมด'||p.category===exportCategory)),[availableProducts,exportCategory]);
  async function read(file:File|undefined){if(!file)return;setError('');setRows([]);setDone(0);setResult('');setBatchId(crypto.randomUUID());try{if(!/\.xlsx?$/i.test(file.name)||file.size>8*1024*1024)throw Error('เลือกไฟล์ .xls หรือ .xlsx ไม่เกิน 8 MB');const XLSX=await import('xlsx');const w=XLSX.read(await file.arrayBuffer(),{type:'array'}),raw=XLSX.utils.sheet_to_json<any>(w.Sheets[w.SheetNames[0]],{defval:''}).filter((x:any)=>!(x['Product detail']==='Total inventory cost'&&!x['Product name']&&!x['Product code']));if(!raw.length||raw.length>5000)throw Error('รองรับ 1–5,000 รายการต่อไฟล์');const mapped=raw.map((x,i)=>{const val=(en:string,th:string)=>x[en]??x[th]??'',sourceQty=Number(val('Quantity','จำนวน')),unlimited=String(val('Unlimited stock (true or false)','สต๊อกไม่จำกัด')).trim().toLowerCase()==='true'||sourceQty===999999;const category=String(val('Category','หมวดหมู่')||'อุปกรณ์เสริม').trim();const r={name:String(val('Product name','ชื่อสินค้า')).trim(),barcode:String(val('Product code','รหัสสินค้า')).trim(),scanCode:String(val('Custom barcode id','บาร์โค้ด')).trim(),category:category==='เอ็น'?'เอ็นแบดมินตัน':category,qty:unlimited?0:sourceQty,unlimited,price:Number(val('Price','ราคาขาย')),cost:val('Cost','ต้นทุน')===''?null:Number(val('Cost','ต้นทุน')),unit:String(val('Unit','หน่วย')||'ชิ้น'),lowStock:Number(val('Notify when product less than','แจ้งเตือนเมื่อเหลือน้อยกว่า')===''?5:val('Notify when product less than','แจ้งเตือนเมื่อเหลือน้อยกว่า'))};if(!r.name||!Number.isInteger(r.qty)||!Number.isFinite(r.price)||r.price<0||!Number.isInteger(r.lowStock)||r.lowStock<0||(r.cost!==null&&(!Number.isFinite(r.cost)||r.cost<0)))throw Error('ข้อมูลไม่ถูกต้องที่แถว '+(i+2));return r;});setRows(mapped);}catch(e:any){setError(e.message)}}
  async function save(){setBusy(true);setError('');try{for(let i=done;i<rows.length;i+=50){const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'importProducts',requestId:batchId+'-'+i,rows:rows.slice(i,i+50)})}),r:any=await response.json();if(!response.ok)throw Error(r.error);setDone(Math.min(i+50,rows.length));}setResult('นำเข้าสินค้าสำเร็จ รหัสหรือบาร์โค้ดที่มีอยู่ถูกข้ามโดยไม่เปลี่ยนยอดเดิม');await reload();}catch(e:any){setError(e.message+' กดนำเข้าต่อได้ โดยไม่บันทึกชุดที่สำเร็จซ้ำ');}finally{setBusy(false)}}
  async function exportExcel(){const chosen=exportRows.filter(p=>selected.length===0||selected.includes(p.id));if(!chosen.length){setError('ไม่พบสินค้าสำหรับส่งออก');return}setBusy(true);setError('');try{const XLSX=await import('xlsx'),sheet=XLSX.utils.json_to_sheet(chosen.map(p=>({'รหัสสินค้า':p.barcode,'ชื่อสินค้า':p.name,'บาร์โค้ด':p.scan_code||'','หมวดหมู่':p.category,'จำนวน':p.stock,'หน่วย':p.unit,'ต้นทุน':p.cost===null?'':p.cost/100,'ราคาขาย':p.price/100,'แจ้งเตือนเมื่อเหลือน้อยกว่า':p.low_stock})));sheet['!cols']=[{wch:20},{wch:38},{wch:20},{wch:24},{wch:12},{wch:12},{wch:14},{wch:14},{wch:28}];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'สินค้า');XLSX.writeFile(book,`wingpro-products-${new Date().toISOString().slice(0,10)}.xlsx`);setResult(`ส่งออก ${chosen.length} รายการเรียบร้อยแล้ว`)}catch(e:any){setError(e.message||'ส่งออกไฟล์ไม่สำเร็จ')}finally{setBusy(false)}}
  return <section className="excel-manager">
    <div className="excel-manager-head"><div><h2>จัดการสินค้าด้วย Excel</h2><p>นำเข้ารายการสินค้าใหม่ หรือนำข้อมูลสินค้าออกไปใช้งานต่อ</p></div><FileSpreadsheet size={30}/></div>
    <div className="excel-tabs"><button type="button" className={mode==='import'?'is-active':''} onClick={()=>{setMode('import');setError('');setResult('')}}><UploadCloud size={18}/>นำเข้าสินค้า</button><button type="button" className={mode==='export'?'is-active':''} onClick={()=>{setMode('export');setError('');setResult('')}}><Download size={18}/>ส่งออกสินค้า</button></div>
    {mode==='import'?<div className="excel-body"><label className="excel-drop"><UploadCloud size={58}/><b>{rows.length?'เลือกไฟล์ใหม่':'คลิกเพื่อเลือกไฟล์ Excel'}</b><span>.xls หรือ .xlsx ขนาดไม่เกิน 8 MB</span><input type="file" accept=".xls,.xlsx" disabled={busy} onChange={e=>read(e.target.files?.[0])}/></label>{!!rows.length&&<><div className="excel-summary"><b>ตรวจสอบก่อนนำเข้า</b><span>{rows.length} รายการ · สต๊อกติดลบ {rows.filter(r=>r.qty<0).length} · สต๊อกไม่จำกัด {rows.filter(r=>r.unlimited).length}</span></div><div className="excel-table-wrap"><table><thead><tr><th>รหัส</th><th>สินค้า</th><th>หมวดหมู่</th><th>จำนวน</th><th>หน่วย</th><th>ต้นทุน</th><th>ราคาขาย</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.barcode||'อัตโนมัติ'}</td><td><b>{r.name}</b>{r.scanCode&&<small>{r.scanCode}</small>}</td><td>{r.category}</td><td>{r.unlimited?'ไม่จำกัด':r.qty}</td><td>{r.unit}</td><td>{r.cost===null?'—':'฿'+r.cost.toLocaleString()}</td><td>฿{r.price.toLocaleString()}</td></tr>)}</tbody></table></div><div className="excel-footer"><p>หมวดหมู่ใหม่จะถูกสร้างอัตโนมัติ · สต๊อกไม่จำกัดหรือ 999999 จะเริ่มที่ 0</p><button disabled={busy||done===rows.length} onClick={save}>{busy?'กำลังนำเข้า…':done?'นำเข้าต่อ':'ยืนยันนำเข้าสินค้า'} ({done}/{rows.length})</button></div></>}</div>:<div className="excel-body"><div className="excel-export-tools"><label><span>เลือกตามหมวดหมู่</span><select value={exportCategory} onChange={e=>{setExportCategory(e.target.value);setSelected([])}}><option>ทั้งหมด</option>{availableCategories.filter(c=>c!=='ทั้งหมด').map(c=><option key={c}>{c}</option>)}</select></label><div><b>{selected.length?`เลือกแล้ว ${selected.length} รายการ`:`ทั้งหมด ${exportRows.length} รายการ`}</b><small>หากไม่เลือกสินค้า ระบบจะส่งออกทุกรายการในหมวดหมู่</small></div><button type="button" disabled={busy||!exportRows.length} onClick={exportExcel}><Download size={18}/>{busy?'กำลังสร้างไฟล์…':'ส่งออก Excel'}</button></div><div className="excel-table-wrap export"><table><thead><tr><th><input type="checkbox" aria-label="เลือกสินค้าทั้งหมด" checked={exportRows.length>0&&exportRows.every(p=>selected.includes(p.id))} onChange={e=>setSelected(e.target.checked?exportRows.map(p=>p.id):[])}/></th><th>สินค้า</th><th>รหัส</th><th>หมวดหมู่</th><th>คงเหลือ</th><th>ราคาขาย</th><th>ราคาทุน</th></tr></thead><tbody>{exportRows.map(p=><tr key={p.id}><td><input type="checkbox" aria-label={'เลือก '+p.name} checked={selected.includes(p.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,p.id]:ids.filter(id=>id!==p.id))}/></td><td><b>{p.name}</b><small>{p.unit}</small></td><td>{p.barcode}</td><td>{p.category}</td><td>{p.stock}</td><td>฿{(p.price/100).toLocaleString()}</td><td>{p.cost===null?'—':'฿'+(p.cost/100).toLocaleString()}</td></tr>)}</tbody></table></div></div>}
    {error&&<p role="alert" className="notice excel-message">{error}</p>}{result&&<p role="status" className="notice excel-message success">{result}</p>}
  </section>
}
