import {sqliteTable,text,integer,index} from 'drizzle-orm/sqlite-core';
export const config=sqliteTable('config',{id:integer('id').primaryKey(),revision:integer('revision').notNull().default(0),nextProductNumber:integer('next_product_number').notNull().default(1),showEarnings:integer('show_earnings').notNull().default(0),shop:text('shop').notNull().default('Badminton Shop'),lineOa:text('line_oa').notNull().default('')});
export const members=sqliteTable('members',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),role:text('role').notNull(),active:integer('active').notNull().default(1)});
export const products=sqliteTable('products',{id:text('id').primaryKey(),name:text('name').notNull(),barcode:text('barcode').notNull().unique(),category:text('category').notNull(),price:integer('price').notNull(),cost:integer('cost'),scanCode:text('scan_code'),lowStock:integer('low_stock').notNull().default(5),image:text('image'),active:integer('active').notNull().default(1),stock:integer('stock').notNull().default(0),unit:text('unit').notNull().default('ชิ้น')});
export const receipts=sqliteTable('receipts',{id:text('id').primaryKey(),productId:text('product_id').notNull(),qty:integer('qty').notNull(),cost:integer('cost'),staffId:text('staff_id').notNull(),created:text('created').notNull()});
export const sales=sqliteTable('sales',{id:text('id').primaryKey(),staffId:text('staff_id').notNull(),created:text('created').notNull(),total:integer('total').notNull(),discount:integer('discount').notNull(),method:text('method').notNull(),slip:text('slip'),jobId:text('job_id').unique()});
export const items=sqliteTable('items',{id:text('id').primaryKey(),saleId:text('sale_id').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),category:text('category').notNull(),qty:integer('qty').notNull(),price:integer('price').notNull(),original:integer('original').notNull(),net:integer('net').notNull(),lineDiscount:integer('line_discount').notNull().default(0),cost:integer('cost'),note:text('note').notNull()},t=>[index('items_sale').on(t.saleId)]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),token:text('token').notNull().unique(),customer:text('customer').notNull(),phone:text('phone').notNull(),racket:text('racket').notNull(),productId:text('product_id').notNull(),tension:text('tension').notNull(),condition:text('condition').notNull(),note:text('note').notNull(),photos:text('photos').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),paid:integer('paid').notNull().default(0),staffId:text('staff_id').notNull(),stringerId:text('stringer_id').notNull(),created:text('created').notNull(),completed:text('completed'),returned:text('returned'),lineUser:text('line_user'),notify:text('notify').notNull().default('ยังไม่เชื่อม LINE')});
export const leaves=sqliteTable('leaves',{id:text('id').primaryKey(),staffId:text('staff_id').notNull(),start:text('start').notNull(),end:text('end').notNull(),type:text('type').notNull(),reason:text('reason').notNull(),status:text('status').notNull(),note:text('note').notNull().default('')});
export const expenses=sqliteTable('expenses',{id:text('id').primaryKey(),date:text('date').notNull(),category:text('category').notNull().default('อื่น ๆ'),photos:text('photos').notNull().default('[]'),name:text('name').notNull(),amount:integer('amount').notNull()});
export const files=sqliteTable('files',{id:text('id').primaryKey(),staffId:text('staff_id').notNull(),mime:text('mime').notNull(),name:text('name').notNull()});
export const operations=sqliteTable('operations',{id:text('id').primaryKey(),staffId:text('staff_id').notNull(),action:text('action').notNull(),created:text('created').notNull(),valid:integer('valid').notNull()});

export const productCategories=sqliteTable("product_categories",{name:text("name").primaryKey().notNull()});

export const stockAdjustments=sqliteTable("stock_adjustments",{id:text("id").primaryKey(),productId:text("product_id").notNull(),delta:integer("delta").notNull(),reason:text("reason").notNull(),staffId:text("staff_id").notNull(),created:text("created").notNull()});
